version: "3.8"

services:
  bikot-web:
    image: ghcr.io/thiagomarianols/bikot:latest

    ports:
      - "8000:8000"

    security_opt:
      - no-new-privileges:true

    tmpfs:
      - /tmp
      - /var/tmp

    cap_drop:
      - ALL

    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - ESP32_API_KEY=${ESP32_API_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

    volumes:
      - media_data:/app/media

    entrypoint:
      - /app/entrypoint.sh

    extra_hosts:
      - "host.docker.internal:host-gateway"

    deploy:
      replicas: 1

      restart_policy:
        condition: on-failure
        delay: 5s

volumes:
  media_data: