# Generated by Django 6.0.5 on 2026-05-26 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True, verbose_name='UID do Crachá')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tag RFID',
                'verbose_name_plural': 'Tags RFID',
                'ordering': ['uid'],
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('rfid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aluno', to='core.rfidtag', verbose_name='RFID / Crachá')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número da Vaga')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupada', 'Ocupada'), ('bloqueada', 'Bloqueada')], default='disponivel', max_length=20, verbose_name='Status')),
                ('pending_unlock', models.BooleanField(default=False, verbose_name='Destravamento Pendente')),
                ('aluno_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaga_atual', to='core.aluno', verbose_name='Aluno Atual')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_uid', models.CharField(max_length=50, verbose_name='UID do RFID')),
                ('acao', models.CharField(choices=[('entrada', 'Entrada (Estacionar)'), ('saida', 'Saída (Retirar)'), ('liberacao_manual', 'Liberação Manual'), ('bloqueio', 'Bloqueio'), ('desbloqueio', 'Desbloqueio'), ('destravamento_remoto', 'Destravamento Remoto')], max_length=30, verbose_name='Ação')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_movimentacao', to='core.aluno', verbose_name='Aluno')),
                ('vaga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_movimentacao', to='core.vaga', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Registro de Movimentação',
                'verbose_name_plural': 'Registros de Movimentação',
                'ordering': ['-timestamp'],
            },
        ),
    ]
