# Generated by Django 6.0.5 on 2026-05-27 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDCadastroPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('success', 'Sucesso'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('scanned_uid', models.CharField(blank=True, max_length=50, null=True, verbose_name='UID Escaneado')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Início')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cadastro_pendente', to='core.aluno', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Cadastro Pendente de RFID',
                'verbose_name_plural': 'Cadastros Pendentes de RFID',
            },
        ),
    ]
