# Generated by Django 6.0.5 on 2026-06-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rfidcadastropendente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Texto do Aviso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Criação')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
