# Generated by Django 6.0.5 on 2026-06-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Expiração'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='avisos/', verbose_name='Foto/Anúncio'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link (Gera QR Code)'),
        ),
    ]
