# Generated by Django 6.0.5 on 2026-06-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aviso_data_expiracao_aviso_foto_aviso_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='foto_fit',
            field=models.CharField(choices=[('cover', 'Preencher (Pode cortar bordas)'), ('contain', 'Ajustar (Não corta, pode deixar bordas)')], default='cover', max_length=10, verbose_name='Ajuste da Foto na TV'),
        ),
    ]
